//! Product capability profiles mirror the existing Go contract.
pub const SENA_MVT: &str = "sena_mvt";
pub fn tool_allowed(profile: &str, connector: &str, operation: &str) -> bool {
    profile != SENA_MVT || ALLOWED.contains(&(connector, operation))
}
pub fn profile_connectors(profile: &str) -> Option<std::collections::BTreeSet<&'static str>> {
    (profile == SENA_MVT).then(|| ALLOWED.iter().map(|(c, _)| *c).collect())
}
const ALLOWED: &[(&str, &str)] = &[
    ("apollo", "people.search"),
    ("apollo", "people.match"),
    ("apollo", "people.bulk_match"),
    ("apollo", "organizations.search"),
    ("apollo", "organizations.enrich"),
    ("apollo", "organizations.bulk_enrich"),
    ("apollo", "organizations.job_postings"),
    ("apollo", "contacts.create"),
    ("apollo", "contacts.update"),
    ("apollo", "contacts.search"),
    ("apollo", "accounts.create"),
    ("apollo", "accounts.update"),
    ("apollo", "email_accounts.list"),
    ("apollo", "users.search"),
    ("brevo", "contacts.create"),
    ("brevo", "contacts.get"),
    ("brevo", "contacts.update"),
    ("brevo", "lists.create"),
    ("brevo", "lists.get"),
    ("brevo", "contacts.addToList"),
    ("brevo", "contacts.removeFromList"),
    ("brevo", "emailCampaigns.create"),
    ("brevo", "emailCampaigns.get"),
    ("brevo", "emailCampaigns.send"),
    ("brevo", "smtp.email.send"),
    ("google-workspace", "sheets.values.get"),
    ("google-workspace", "sheets.values.append"),
    ("google-workspace", "sheets.values.update"),
    ("google-workspace", "sheets.values.clear"),
    ("google-workspace", "sheets.spreadsheets.create"),
    ("google-workspace", "sheets.spreadsheets.batchUpdate"),
    ("rb2b", "visitors.parse"),
    ("unipile", "accounts.get"),
    ("unipile", "accounts.list"),
    ("unipile", "chats.get"),
    ("unipile", "chats.list"),
    ("unipile", "chats.start"),
    ("unipile", "emails.get"),
    ("unipile", "emails.list"),
    ("unipile", "emails.send"),
    ("unipile", "linkedin.invitation.send"),
    ("unipile", "linkedin.profile.get"),
    ("unipile", "linkedin.relations.list"),
    ("unipile", "messages.list"),
    ("unipile", "messages.send"),
    ("apify", "actor.run"),
    ("apify", "actor.run_sync_get_dataset_items"),
    ("apify", "actors.get"),
    ("apify", "actors.list"),
    ("apify", "datasets.get"),
    ("apify", "datasets.items"),
    ("apify", "runs.get"),
    ("apify", "runs.list"),
    ("apify", "task.run"),
    ("apify", "task.run_sync_get_dataset_items"),
    ("apify", "tasks.list"),
    ("cal-com", "bookings.create"),
    ("cal-com", "bookings.get"),
    ("cal-com", "bookings.list"),
    ("cal-com", "bookings.reschedule"),
    ("cal-com", "event_types.get"),
    ("cal-com", "event_types.list"),
    ("cal-com", "me.get"),
    ("cal-com", "schedules.list"),
    ("cal-com", "slots.available"),
    ("calendly", "bookings.create"),
    ("calendly", "event_types.list"),
    ("calendly", "scheduled_events.get"),
    ("calendly", "scheduled_events.invitees.list"),
    ("calendly", "scheduled_events.list"),
    ("calendly", "scheduling_links.create"),
    ("calendly", "slots.available"),
    ("calendly", "users.me.action"),
    ("googlemeet", "meetings.create"),
    ("googlemeet", "meetings.list"),
];
