import { curatedTemplates } from "./templates";
import type { DeclarativeManifest } from "../../../../runner/bun/src/declarative/types";
import type { StaticProvider, HoldReason } from "./static-parser";
import type { ReviewedAdapter } from "./adapters";
import { approvedContracts } from "./contracts";
export type Adapter = ReviewedAdapter;
export type ConvertResult = { manifest?: DeclarativeManifest; holds: HoldReason[]; provenance?: { manifestPath: string } };
export async function convert(provider: StaticProvider, adapters: readonly Adapter[], selected: readonly string[], templates?: Readonly<Record<string, DeclarativeManifest>>): Promise<ConvertResult> {
  const holds: HoldReason[] = [], mappings = adapters.filter(a => a.providerId === provider.id);
  const templatePath = mappings[0]?.manifestPath; if (!templatePath) return { holds: [{ providerId: provider.id, code: "MISSING_MAPPING", detail: "reviewed adapter mapping is required" }] };
  const contract = approvedContracts[provider.id as keyof typeof approvedContracts] as any;
  if (!contract) return { holds: [{ providerId: provider.id, code: "UNKNOWN_PROVIDER", detail: "provider has no approved contract" }] };
  const templateKey = contract.templateKey ?? contract.appcallId ?? provider.id;
  let template: DeclarativeManifest; try { template = (templates && Object.prototype.hasOwnProperty.call(templates, templateKey) ? templates[templateKey] : (curatedTemplates as any)[templateKey]) as DeclarativeManifest; if (!template || typeof template !== "object") throw new Error("null template"); } catch { return { holds: [{ providerId: provider.id, code: "MISSING_TEMPLATE", detail: "reviewed manifest template cannot be loaded" }] }; }
  const operations: Record<string, any> = {};
  const allowed = contract.allowedHosts; const expectedBase = contract.baseUrl;
  const auth = template.auth as any; const oauth = auth?.oauth;
  const authOk = auth?.type === contract.authType && auth.setup?.mode === contract.setupMode && (auth?.type === "oauth2" ? Array.isArray(auth.setup?.fields) && (!contract.oauth || (oauth?.authorizeUrl === contract.oauth.authorizeUrl && oauth?.tokenUrl === contract.oauth.tokenUrl)) : (!contract.authField || auth.setup?.fields?.some((f: any) => f.key === contract.authField && f.secret === true)));
  if (template.key !== (contract.appcallId ?? provider.id) || template.runtime !== "bun" || !Array.isArray(template.models) || template.models.length === 0 || template.http?.baseUrl !== expectedBase || JSON.stringify([...(template.network?.allowedHosts ?? [])].sort()) !== JSON.stringify([...allowed].sort()) || !authOk || (contract.httpAuth && JSON.stringify(template.http?.auth) !== JSON.stringify(contract.httpAuth))) return { holds: [{ providerId: provider.id, code: "INVALID_TEMPLATE", detail: "identity, runtime, models, auth, base URL or network allowlist is invalid" }] };
  if (mappings.some(a => mappings.filter(x => x.appcallOperationId === a.appcallOperationId).length !== 1)) return { holds: [{ providerId: provider.id, code: "DUPLICATE_MAPPING", detail: "each AppCall operation requires exactly one mapping" }] };
  for (const operationId of selected) { const candidates = mappings.filter(a => a.appcallOperationId === operationId); const adapter = candidates.length === 1 ? candidates[0] : undefined; const metadata = adapter && provider.actions.find(a => a.id === adapter.upstreamActionId); const op = (template.operations as any)?.[operationId]; const expectedMethod = contract.operationMethods?.[operationId]; const bounds = op && [op.timeoutMs, op.maxInputBytes, op.maxResponseBytes].every((n: unknown) => Number.isSafeInteger(n) && (n as number) > 0 && (n as number) <= 30_000_000); if (!expectedMethod || !metadata || !op || op.kind !== "action" || op.sideEffect !== "read" || op.request?.method !== expectedMethod || JSON.stringify(op.request.success) !== "[200]" || op.request.baseUrl || !bounds || !op.inputSchema || typeof op.inputSchema !== "object" || Array.isArray(op.inputSchema) || !op.outputSchema || typeof op.outputSchema !== "object" || Array.isArray(op.outputSchema) || op.enforceOutputSchema !== true || !String(op.request.path ?? "").startsWith("/") || String(op.request.path).startsWith("//") || /:\/\//.test(op.request.path) || /[?#]/.test(op.request.path)) { holds.push({ providerId: provider.id, actionId: operationId, code: "UNSAFE_TEMPLATE", detail: "template operation fails reviewed method, mapping, schema, URL or bounds validation" }); continue; } operations[operationId] = structuredClone(op); }
  if (holds.length || Object.keys(operations).length !== selected.length) return { holds }; const manifest = structuredClone(template); manifest.operations = operations; return { manifest, holds, provenance: { manifestPath: templatePath } };
}
