import { mkdir, readFile, lstat, readdir, realpath, writeFile } from "node:fs/promises";
import { join, resolve, dirname, basename } from "node:path";
import { tmpdir } from "node:os";
import { createHash } from "node:crypto";
import { readRecipe } from "./recipes";
import { loadFixtureCases } from "./recipe-fixtures";
import { buildRecipeCatalog } from "./recipe-build";
import type { RecipeRecord, BuiltArtifact } from "./recipe-build";
import { fingerprintRuntime } from "./runtime-fingerprint";

const sha=(v: string|Uint8Array)=>createHash("sha256").update(v).digest("hex");
const fail=(m:string):never=>{throw new Error(m)};
const MAX_FILE=10*1024*1024;
async function ensureNoSymlinks(root:string):Promise<void>{const st=await lstat(root);if(st.isSymbolicLink())fail("unsafe fixture path");if(!st.isDirectory())fail("unsafe fixture path");for(const name of await readdir(root)){const p=join(root,name);const child=await lstat(p);if(child.isSymbolicLink())fail("unsafe fixture path");if(child.isDirectory())await ensureNoSymlinks(p);}}
async function safeReadUnder(root:string, candidate:string):Promise<Uint8Array>{const base=resolve(root);const lexical=resolve(base,candidate);if(!lexical.startsWith(base+"/"))fail("unsafe fixture path");let cur=base;for(const part of lexical.slice(base.length+1).split("/")){cur=join(cur,part);const st=await lstat(cur);if(st.isSymbolicLink()||st.size>MAX_FILE)fail("unsafe fixture path");}const st=await lstat(lexical);if(!st.isFile()||st.isSymbolicLink())fail("unsafe fixture path");const bytes=await readFile(lexical);if(bytes.byteLength>MAX_FILE)fail("unsafe fixture path");return bytes}
export async function emitVerifiedCatalog(build:{records: readonly RecipeRecord[]; artifacts: Record<string, BuiltArtifact>; asOf?: string}, outDir:string):Promise<Record<string,unknown>> {
  const target=resolve(outDir); if(dirname(target)!==resolve(tmpdir())) fail("staging directory must be a fresh direct temp child");
  try { await lstat(target); fail("staging directory already exists"); } catch(e:any) { if(e?.code !== "ENOENT") throw e; }
  const accepted:any[]=[]; const seen=new Set<string>(); const runtimeBaseline=await fingerprintRuntime();
  for(const row of build.records){ if(!/^[a-z0-9][a-z0-9_-]*$/.test(row.providerId)) fail("invalid provider identity"); if(row.appcallId && !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(row.appcallId)) fail("invalid connector identity"); if(row.appcallId && seen.has(row.appcallId)) fail("duplicate connector identity"); if(row.appcallId) seen.add(row.appcallId); if(row.status!=="ACCEPTED") continue; const artifact=build.artifacts[row.appcallId]; if(!artifact) fail("accepted result missing artifact");
    await ensureNoSymlinks(artifact.recipeDir);
    const canonicalRecipeRoot=await realpath(artifact.recipeDir); const recipe=await readRecipe(canonicalRecipeRoot); const casesDir=join(canonicalRecipeRoot,"fixtures/cases"); const fixtureRoot=join(canonicalRecipeRoot,"fixtures");
    const cases=loadFixtureCases(casesDir);
    if(!build.asOf) fail("build result missing asOf"); const rebuilt=await buildRecipeCatalog({recipes:[recipe],asOf:build.asOf,snapshot:{root:artifact.sourceRoot},recipeDirs:{[recipe.providerId]:canonicalRecipeRoot},fixtureCases:()=>cases}); const after=await fingerprintRuntime(); if(runtimeBaseline.aggregateHash!==after.aggregateHash) fail("runtime changed during fixture verification");
    const record=rebuilt.records.find(x=>x.appcallId===row.appcallId); if(!record||record.status!=="ACCEPTED") fail("accepted record did not rebuild and pass verification");
    const verifiedArtifact=rebuilt.artifacts[row.appcallId]; if(!verifiedArtifact) fail("verified artifact missing"); const fixtureFiles:Record<string,Uint8Array>={}; const copiedHashes:string[]=[]; for(const c of cases as any[]){const casePath=resolve(c._file!); const refs=[casePath,...(c.exchanges??[]).map((e:any)=>resolve(dirname(casePath),e.response.bodyFile)),...(c.expected?.kind==="success"?[resolve(dirname(casePath),c.expected.resultFile)]:[])]; for(const path of refs){const bytes=await safeReadUnder(fixtureRoot,path); copiedHashes.push(sha(bytes)); fixtureFiles["fixtures/"+resolve(path).slice(resolve(fixtureRoot).length+1).split("/").join("/")]=bytes;}} const runs=(record.fixture??[]) as any[]; const rebuiltHashes=runs.flatMap(x=>x.fixtureHashes??[]); if(JSON.stringify(copiedHashes)!==JSON.stringify(rebuiltHashes)) fail("copied fixture hashes differ from rebuilt verification"); const readme=await safeReadUnder(artifact.recipeDir,"README.md"); const authoritative={...record,sourceHashes:verifiedArtifact.sourceHashes,recipeHash:sha(verifiedArtifact.recipeBytes)}; accepted.push({row,artifact:{...verifiedArtifact,fixtureFiles,readmeBytes:readme},record:authoritative});
  }
  await mkdir(target); const licenseDir=join(target,"third_party/licenses/openconnector"); await mkdir(licenseDir,{recursive:true}); const licenseRoot=new URL("../../../third_party/licenses/openconnector/",import.meta.url); await writeFile(join(licenseDir,"LICENSE"),await readFile(new URL("LICENSE",licenseRoot)),{flag:"wx"}); await writeFile(join(licenseDir,"NOTICE"),await readFile(new URL("NOTICE",licenseRoot)),{flag:"wx"}); for(const {row,artifact} of accepted){const dir=join(target,row.appcallId); await mkdir(dir); await writeFile(join(dir,"manifest.json"),artifact.manifestBytes,{flag:"wx"}); await writeFile(join(dir,"recipe.json"),artifact.recipeBytes,{flag:"wx"}); if(artifact.readmeBytes) await writeFile(join(dir,"README.md"),artifact.readmeBytes,{flag:"wx"}); for(const [path,bytes] of Object.entries(artifact.fixtureFiles)){if(path.startsWith("/")||path.includes("..")||path.includes("\\")) fail("unsafe fixture path"); const out=join(dir,path); await mkdir(dirname(out),{recursive:true}); await writeFile(out,bytes,{flag:"wx"});}}
  const inventory=build.records.map(r=>({providerId:r.providerId,appcallId:r.appcallId,status:r.status,artifactHash:null})); for(const x of inventory){const a=accepted.find(y=>y.row.appcallId===x.appcallId); if(a)x.artifactHash=sha(a.artifact.manifestBytes);}
  const runtimeFingerprint=await fingerprintRuntime(); if(runtimeBaseline.aggregateHash!==runtimeFingerprint.aggregateHash) fail("runtime changed during emission"); const report={schemaVersion:1,asOf:build.asOf,runtimeFingerprint,inventory,rebuilt:accepted.map(x=>x.record),accepted:accepted.map(x=>x.row.appcallId),counts:Object.fromEntries(["ACCEPTED","HOLD","EXCLUDE","existing","FAILED"].map(k=>[k,build.records.filter(r=>r.status.toUpperCase()===k.toUpperCase()).length]))}; await writeFile(join(target,"report.json"),JSON.stringify(report,null,2)+"\n",{flag:"wx"}); return report;
}
