import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readFileSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { loadFixtureCases, runCandidateFixtures, verifyFixtureCoverage } from "../recipe-fixtures";

const manifest = { key:"fixture", runtime:"bun", models:["x"], network:{allowedHosts:["example.test"]}, http:{baseUrl:"https://example.test",auth:{field:"token"}}, operations:{ping:{kind:"action",inputSchema:{type:"object",additionalProperties:false,properties:{}},request:{method:"GET",path:"/ping",success:[200]},outputSchema:{type:"object"},enforceOutputSchema:false}} } as any;
function dir(){const d=mkdtempSync(join(tmpdir(),"appcall-fixture-"));mkdirSync(join(d,"cases"));mkdirSync(join(d,"responses"));mkdirSync(join(d,"expected"));writeFileSync(join(d,"responses/body.json"),'{"ok":true}');writeFileSync(join(d,"expected/result.json"),'{"connector":"fixture","action":"ping","source":"provider","data":{"ok":true}}');return d;}
function fixture(d:string, url="https://example.test/ping"){writeFileSync(join(d,"cases/case.json"),JSON.stringify({schemaVersion:1,id:"ping",operation:"ping",input:{},credentials:{token:"dummy"},evidence:{},exchanges:[{request:{method:"GET",url,headers:{},body:null},response:{status:200,headers:{"content-type":"application/json"},bodyFile:"../responses/body.json"}}],expected:{kind:"success",resultFile:"../expected/result.json"}}));}
describe("recipe fixtures",()=>{
 test("loads and runs exact serialized candidate",async()=>{const d=dir();fixture(d);const c=loadFixtureCases(join(d,"cases"));expect(verifyFixtureCoverage(manifest,c).missing).toEqual([]);expect((await runCandidateFixtures(JSON.stringify(manifest),c))[0]?.status).toBe("passed");});
 test("rejects traversal",()=>{const d=dir();fixture(d);writeFileSync(join(d,"cases/case.json"),readFileSync(join(d,"cases/case.json"),"utf8").replace("../responses/body.json","../../body.json"));expect(()=>loadFixtureCases(join(d,"cases"))).toThrow();});
 test("reports URL mismatch",async()=>{const d=dir();fixture(d,"https://example.test/wrong");expect((await runCandidateFixtures(JSON.stringify(manifest),loadFixtureCases(join(d,"cases"))))[0]?.status).toBe("failed");});
 test("requires positive coverage and rejects duplicates and unknown operations",()=>{const d=dir();fixture(d);const c=loadFixtureCases(join(d,"cases"));expect(()=>verifyFixtureCoverage({...manifest,operations:{ping:{},other:{}}},c)).toThrow(/missing positive/);expect(()=>verifyFixtureCoverage(manifest,[c[0],{...c[0],id:"ping"}])).toThrow(/duplicate/);expect(()=>verifyFixtureCoverage(manifest,[{...c[0],operation:"other"}])).toThrow(/unknown/);});
 test("rejects symlink response files",()=>{const d=dir();symlinkSync(join(d,"responses/body.json"),join(d,"responses/link.json"));fixture(d);const p=join(d,"cases/case.json");writeFileSync(p,readFileSync(p,"utf8").replace("body.json","link.json"));expect(()=>loadFixtureCases(join(d,"cases"))).toThrow(/symlink/);});
 test("does not accept fulfilled fake errors",async()=>{const d=dir();fixture(d);const p=join(d,"cases/case.json");writeFileSync(p,readFileSync(p,"utf8").replace('"kind":"success","resultFile":"../expected/result.json"','"kind":"error","code":"INVALID_ACTION_INPUT"'));expect((await runCandidateFixtures(JSON.stringify(manifest),loadFixtureCases(join(d,"cases"))))[0]?.status).toBe("failed");});
 test("invalid input expects zero dispatch",async()=>{const d=dir();writeFileSync(join(d,"cases/case.json"),JSON.stringify({schemaVersion:1,id:"invalid",operation:"ping",input:{unknown:true},credentials:{token:"dummy"},evidence:{},exchanges:[],expected:{kind:"error",code:"INVALID_ACTION_INPUT"}}));const r=await runCandidateFixtures(JSON.stringify(manifest),loadFixtureCases(join(d,"cases")));expect(r[0]?.status).toBe("passed");expect(r[0]?.calls).toBe(0);});
});
